version: '3.7'

services:
  nginx:
    image: wodby/nginx:1.24
    container_name: nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      NGINX_VHOST_PRESET: drupal10
      NGINX_SERVER_ROOT: /var/www/html/web

  php:
    image: wodby/drupal-php:8.2
    container_name: php
    volumes:
      - ./:/var/www/html
    environment:
      PHP_FPM_LOG_LEVEL: notice
      PHP_FPM_PM_MAX_CHILDREN: 10
      #PHP_MEMORY_LIMIT: 1024M
      PHP_MODULE_REDIS: 1
      #PHP_XDEBUG_CLIENT_HOST: "host.docker.internal"
      #PHP_XDEBUG_MODE: "debug"
      #PHP_EXTENSIONS_DISABLE: "xhprof,spx"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: wodby/mariadb:10.11
    container_name: db
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db

volumes:
  code:
  database:
